import {ILocals} from './Locals';

export const ArabicLocals: ILocals = {
    address: "العنوان",
    city: "المدينة",
    company_name: "اسم الشركة",
    person_name: "الاسم",
    phone: "رقم الهاتف",
    register: 'التسجيل',
    airlines: 'الخطوط الجوية',
    login: 'تسجيل الدخول',
    password: 'كلمة المرور',
    username: 'اسم المستخدم',
    close: 'اغلاق',
    home: 'الرئيسية',
    about_us: 'من نحن',
    contact_us: 'تواصل معنا',
    destinations: 'وجهات سياحية',
    services: 'الخدمات',
    partners: 'الشركاء',
    email: 'البريد الالكتروني',
    message: 'الرسالة',
    name: 'الاسم',
    send: 'ارسال',
    subject: 'الموضوع',
    price: 'السعر',
    description: 'التفاصيل',
    duration: 'المدة',
    for_booking: 'للحجز',
    images: 'الصور'
}